# Generated by Django 6.0.1 on 2026-02-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Ex: #000000', max_length=7, null=True),
        ),
    ]
