# Generated by Django 6.0.1 on 2026-02-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_color_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='product',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Exemple : #FF0000 pour rouge', max_length=7, null=True),
        ),
    ]
