# Generated by Django 6.0.1 on 2026-02-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_color_alter_product_color_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_hex',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Rouge'), ('blue', 'Bleu'), ('green', 'Vert'), ('black', 'Noir'), ('white', 'Blanc'), ('yellow', 'Jaune')], max_length=20, null=True),
        ),
    ]
