# Generated by Django 6.0.1 on 2026-02-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_product_is_parent_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptiondetaillee',
            field=models.TextField(blank=True, verbose_name='Description détaillée'),
        ),
    ]
